# ----------------------------------------------------
# This file is generated by the Qt Visual Studio Add-in.
# ------------------------------------------------------

HEADERS += ../../Clients/FCClient_Qt/CharacterSelectionWidget.h \
    ../../Clients/FCClient_Qt/clientstrings.h \
    ../../Clients/FCClient_Qt/DlgLogin.h \
    ../../Clients/FCClient_Qt/FCApp.h \
    ../../Clients/FCClient_Qt/fcclient_consts.h \
    ../../Clients/FCClient_Qt/fcmainwindow.h \
    ../../Clients/FCClient_Qt/FCModel.h \
    ../../Clients/FCClient_Qt/FCNet.h \
    ../../Clients/FCClient_Qt/FCPlayerModel.h \
    ../../Clients/FCClient_Qt/ItemMgr.h \
    ../../common/PacketExtractor.h \
    ../../Clients/FCClient_Qt/PacketHandler.h \
    ../../common/PEPacket.h \
    ../../common/PEPacketHelper.h \
    ../../Clients/FCClient_Qt/ResourceManager.h \
    ../../Clients/FCClient_Qt/Settings.h \
    ../../Clients/FCClient_Qt/StdAfx.h \
    ../../common/time/timelib.h \
    ../../Clients/FCClient_Qt/ViewBase.h \
    ../../Clients/FCClient_Qt/ViewCharSelection.h \
    ../../Clients/FCClient_Qt/ViewLoading.h \
    ../../common/game_objects/BankAccount.h \
    ../../Clients/FCClient_Qt/dataobjects/Character.h \
    ../../common/game_objects/ComputerBase.h \
    ../../common/game_objects/FCObject.h \
    ../../common/game_objects/InGameIPAddress.h \
    ../../common/game_objects/Item.h \
    ../../common/game_objects/ItemMemory.h \
    ../../common/game_objects/ItemOS.h \
    ../../common/game_objects/ItemProcessor.h \
    ../../common/game_objects/ItemSoftware.h \
    ../../common/game_objects/ItemType.h \
    ../../common/game_objects/NetworkPorts.h \
    ../../common/game_objects/swtypes.h \
    ../../common/pthreads-win32/include/pthread.h \
    ../../common/PThreadRWLock.h
SOURCES += ../../Clients/FCClient_Qt/CharacterSelectionWidget.cpp \
    ../../Clients/FCClient_Qt/DlgLogin.cpp \
    ../../Clients/FCClient_Qt/FCApp.cpp \
    ../../Clients/FCClient_Qt/fcmainwindow.cpp \
    ../../Clients/FCClient_Qt/FCModel.cpp \
    ../../Clients/FCClient_Qt/FCNet.cpp \
    ../../Clients/FCClient_Qt/FCPlayerModel.cpp \
    ../../Clients/FCClient_Qt/ItemMgr.cpp \
    ../../Clients/FCClient_Qt/main.cpp \
    ../../common/PacketExtractor.cpp \
    ../../Clients/FCClient_Qt/PacketHandler.cpp \
    ../../common/PEPacket.cpp \
    ../../common/PEPacketHelper.cpp \
    ../../Clients/FCClient_Qt/ResourceManager.cpp \
    ../../Clients/FCClient_Qt/Settings.cpp \
    ../../Clients/FCClient_Qt/StdAfx.cpp \
    ../../common/time/timelib.cpp \
    ../../Clients/FCClient_Qt/ViewBase.cpp \
    ../../Clients/FCClient_Qt/ViewCharSelection.cpp \
    ../../Clients/FCClient_Qt/ViewLoading.cpp \
    ../../common/game_objects/BankAccount.cpp \
    ../../Clients/FCClient_Qt/dataobjects/Character.cpp \
    ../../common/game_objects/ComputerBase.cpp \
    ../../common/game_objects/FCObject.cpp \
    ../../common/game_objects/InGameIPAddress.cpp \
    ../../common/game_objects/ItemMemory.cpp \
    ../../common/game_objects/ItemOS.cpp \
    ../../common/game_objects/ItemProcessor.cpp \
    ../../common/game_objects/ItemSoftware.cpp \
    ../../common/game_objects/NetworkPorts.cpp \
    ../../common/PThreadRWLock.cpp
FORMS += ../../Clients/FCClient_Qt/ui/CharacterSelectionWidget.ui \
    ../../Clients/FCClient_Qt/ui/DlgLogin.ui \
    ../../Clients/FCClient_Qt/ui/fcmainwindow.ui \
    ../../Clients/FCClient_Qt/ui/ViewCharSelection.ui \
    ../../Clients/FCClient_Qt/ui/ViewLoading.ui
RESOURCES += ./fcclient_qt.qrc
